### ISSUE TITLE
Multiple token values in cookies

### ISSUE THREAD

**Issue by tapkain** [colinhacks/next-firebase-ssr#4]
Hi, thank you for the awesome example, I love the way you designed so elegant the auth solution.
I was playing around and encountered that there are multiple cookies with the value token and I'm sure it comes from nookies. One major bug that could happen is that one of those token values can be undefined and then the client will be in such state where it is logged in via firebase but because of bad cookies the page won't be rendered if getServerSideProps check for token. Do you know what could be the reason for this or it is just my local dev environment?

**Comment by colinhacks** [comment]
I'm having trouble replicating this. What is the behavior you're seeing? In `authenticated.tsx`, are you getting multiple values in `cookies.token` somehow? Or are you just seeing multiple tokens in the `document.cookie`?

In any case I pushed a patch that deletes the old token before setting the new one which should resolve any potential issues. 👍

```ts
nookies.destroy(null, "token");
nookies.set(null, "token", token, {});
```

**Comment by tapkain** [comment]
Hey, it is usually when the session was expired or I was re-logging in. Found out by myself that when user was null the token was set as an empty string value instead of deleting it from cookies. The fix is similar to yours, so I think that should address the issue. Thank you!
