### ISSUE TITLE
Token duplication

### ISSUE THREAD

**Issue by tapkain** [colinhacks/next-firebase-ssr#6]
Hi, I've got again duplicated tokens, even with the recent fixes. Cannot attach steps to reproduce, but what I was doing is login in and out from time to time and then somehow I've got those duplicates. Attached screenshot for more clarity.

https://prnt.sc/vufsay

**Comment by tapkain** [comment]
Hmm, maybe it is because I have sign in flow from different parts of my application and the cookie path should be specified explicitly as global
nookies.set(null, 'token', token, { path: '/' });

**Comment by wRWebDev** [comment]
Thanks, @tapkain - Adding a fixed path attribute to the cookie solved the issue of multiplying cookies for me too 🙌

**Comment by colinhacks** [comment]
If someone submits this change as a PR I'll accept it.

**Comment by mimiqkz** [comment]
Why is there an error like this to begin with ? Is that because of the nookies package?

**Comment by colinhacks** [comment]
Fixed by #11, thanks @tapkain @wRWebDev!

I've also fixed the blog post.
