### ISSUE TITLE
Remember me feature direction

### ISSUE THREAD

**Issue by indralukmana** [colinhacks/next-firebase-ssr#8]
Hi @colinhacks 

Thank you for the repo and your article on Next.js Firebase auth. They are really helpful!

I'm wondering if we can have something like "Remember Me" when sign-in using the techniques you explained. I see that the persistence set as `session` in `firebaseClient.ts`.

```jsx
firebaseClient
    .auth()
    .setPersistence(firebaseClient.auth.Auth.Persistence.SESSION);
```

I read the auth-persistence article in Firebase [link](https://firebase.google.com/docs/auth/web/auth-state-persistence) and I was thinking of making a switch/checkbox in login page that set the session. A base example logic would be like this:

```jsx

if (rememberMeCheckboxIsChecked){
  firebaseClient
      .auth()
      .setPersistence(firebaseClient.auth.Auth.Persistence.LOCAL);
} else {
  firebaseClient
      .auth()
      .setPersistence(firebaseClient.auth.Auth.Persistence.SESSION);
}
```

Do you think something like this would be possible or do you there will be pitfalls doing the "Remember me" this way?

**Comment by colinhacks** [comment]
I think this should work fine! But remember that `setPersistence`returns a Promise, and you'll want to make sure it resolved before you try signing the user in:

```ts
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.SESSION)
  .then(() => {
    // Existing and future Auth states are now persisted in the current
    // session only. Closing the window would clear any existing state even
    // if a user forgets to sign out.
    // ...
    // New sign-in will be persisted with session persistence.
    return firebase.auth().signInWithEmailAndPassword(email, password);
  })
  .catch((error) => {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
  });

```
